export interface Property {
  id: string;
  name: string;
  location: string;
  price: number;
  sqft: number;
  suites: number;
  vibeTags: string[];
  description: string;
  image: string;
  panorama: string;
}

export const PROPERTIES: Property[] = [
  {
    id: "villa-morpho",
    name: "Villa Morpho",
    location: "Papagayo Peninsula",
    price: 12500000,
    sqft: 8500,
    suites: 6,
    vibeTags: ["Oceanfront", "Infinity View", "Eco-Luxury"],
    description: "A breathtaking architectural masterpiece designed to mimic the wings of a Morpho butterfly. Features seamless indoor-outdoor living with panoramic ocean views.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "obsidian-canopy",
    name: "The Obsidian Canopy",
    location: "Santa Teresa",
    price: 8900000,
    sqft: 6200,
    suites: 5,
    vibeTags: ["Jungle Brutalism", "Surf Access", "Minimalist"],
    description: "Striking black concrete structures hidden within the dense jungle. Designed for ultimate privacy while remaining steps away from world-class surf.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "quepos-zenith",
    name: "Quepos Zenith",
    location: "Manuel Antonio",
    price: 15000000,
    sqft: 12000,
    suites: 8,
    vibeTags: ["Helipad Access", "Cliffside", "Panoramic"],
    description: "Perched on the highest cliff in Manuel Antonio, Zenith offers unparalleled views of the Pacific Ocean and a private path to a secluded beach.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "guanacaste-gold",
    name: "Guanacaste Gold Estate",
    location: "Papagayo Peninsula",
    price: 22000000,
    sqft: 15500,
    suites: 10,
    vibeTags: ["Ultra-Luxury", "Private Beach", "Yacht Mooring"],
    description: "The crown jewel of Papagayo. This estate features its own private white-sand beach, a mega-yacht mooring, and a multi-level cascading infinity pool.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "cloud-forest",
    name: "Cloud Forest Sanctuary",
    location: "Monteverde",
    price: 5500000,
    sqft: 7000,
    suites: 4,
    vibeTags: ["High Altitude", "Sustainable", "Glass House"],
    description: "Suspended in the misty canopy, this glass-walled sanctuary blurs the line between the luxurious interior and the ancient, vibrant cloud forest outside.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "escalante-apex",
    name: "Escalante Apex Penthouse",
    location: "Escalante (Urban Luxury)",
    price: 3200000,
    sqft: 4500,
    suites: 3,
    vibeTags: ["Skyline View", "Smart Home", "Gastronomic Center"],
    description: "The absolute height of urban sophistication. A multi-level penthouse in the heart of San José's culinary district with a private rooftop pool.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "nosara-flow",
    name: "Nosara Flow Villa",
    location: "Nosara",
    price: 6800000,
    sqft: 5800,
    suites: 5,
    vibeTags: ["Wellness", "Open Air", "Yoga Pavilion"],
    description: "Built for harmony and health. Features a dedicated yoga pavilion, salt-water lap pool, and organic gardens, all within walking distance to Guiones.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "casa-jade",
    name: "Casa Jade",
    location: "Santa Teresa",
    price: 4900000,
    sqft: 4200,
    suites: 4,
    vibeTags: ["Tropical Modernism", "Secluded", "Infinity Pool"],
    description: "A masterclass in tropical modernism. Local teak, poured concrete, and lush indoor gardens create a tranquil oasis hidden from the world.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "papagayo-point",
    name: "Point of Papagayo",
    location: "Papagayo Peninsula",
    price: 18500000,
    sqft: 11000,
    suites: 7,
    vibeTags: ["Peninsula Tip", "270° Views", "Golf Cart Access"],
    description: "Situated on the very tip of a private peninsula. Every room offers a different perspective of the Pacific Ocean and the rugged Guanacaste coastline.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "manuel-antonio-reserve",
    name: "The Reserve",
    location: "Manuel Antonio",
    price: 9200000,
    sqft: 8000,
    suites: 6,
    vibeTags: ["Wildlife Integration", "Canopy Walkway", "Exclusive"],
    description: "Bordering the national park, this estate is frequently visited by monkeys and sloths. Includes a private canopy bridge connecting the main house to the guest suites.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "escalante-vault",
    name: "The Vault",
    location: "Escalante (Urban Luxury)",
    price: 2800000,
    sqft: 3800,
    suites: 2,
    vibeTags: ["Industrial Chic", "Art Collector", "City Center"],
    description: "A converted historical building turned into a sprawling, industrial-chic loft. Designed specifically for displaying large-scale contemporary art.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "nosara-horizon",
    name: "Horizon House",
    location: "Nosara",
    price: 7500000,
    sqft: 6500,
    suites: 5,
    vibeTags: ["Sunset Facing", "Minimalist", "Surfer's Dream"],
    description: "Characterized by its massive cantilevered roof that seems to float against the horizon. The ultimate vantage point for Nosara's legendary sunsets.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "santa-teresa-cliff",
    name: "Cliffside Haven",
    location: "Santa Teresa",
    price: 11000000,
    sqft: 9000,
    suites: 6,
    vibeTags: ["Dramatic Elevation", "Private Funicular", "Ocean Sounds"],
    description: "Accessed via a private funicular, this multi-level compound cascades down a sheer cliff face, offering unparalleled privacy and drama.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "papagayo-breeze",
    name: "Papagayo Breeze",
    location: "Papagayo Peninsula",
    price: 14000000,
    sqft: 10500,
    suites: 7,
    vibeTags: ["Marina Views", "Family Estate", "Resort Amenities"],
    description: "A sweeping, elegant estate designed to capture the cross-breezes. Overlooks the prestigious marina and includes access to world-class resort amenities.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
  },
  {
    id: "manuel-antonio-hideaway",
    name: "The Hideaway",
    location: "Manuel Antonio",
    price: 4200000,
    sqft: 4000,
    suites: 3,
    vibeTags: ["Intimate", "Rainforest", "Creek-side"],
    description: "An intimate, beautifully crafted wooden home nestled next to a pristine rainforest creek. The sound of running water provides a constant, soothing soundtrack.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
  }
];
