export interface Property {
  id: string;
  name: string;
  location: string;
  price: number;
  sqft: number;
  suites: number;
  vibeTags: string[];
  description: string;
  image: string;
  panorama: string;
  type: "Casa" | "Cabaña" | "Quinta" | "Lote" | "Quinta de Descanso" | "Terreno de Montaña" | "Villa Exclusiva" | "Edificio" | "Bodega";
  segment: "Luxury" | "Standard" | "Commercial";
  province: "San José" | "Alajuela" | "Cartago" | "Heredia" | "Guanacaste" | "Puntarenas" | "Limón";
  lifestyle: "Naturaleza" | "Ciudad";
  status: "Disponible" | "Opcionada" | "Vendida" | "Destacada";
  approxLocation: string;
  // Security-First Logistics & Style of Life Metrics
  elevationM: number;
  airportDistKm: number;
  airportTimeMin: number;
  closestCity: string;
  cityDistKm: number;
  medicalDistMin: number;
  hasFiberOptic: boolean;
  hasStarlink: boolean;
  gallery?: string[];
  nameEs?: string;
  descriptionEs?: string;
  refCode?: string;
  fincaRegistryNum?: string;
  catasterMapNum?: string;
}

export interface Lead {
  id: string;
  name: string;
  email: string;
  phone: string;
  budgetRange: string;
  financing: string;
  horizon: string;
  motivation: string;
  wishlistPropertyIds: string[];
  status: "Lead Nuevo" | "En Contacto" | "Discovery Tour Programado" | "Propuesta/Negociación" | "Cierre Exitoso / Perdido";
  tourDates?: string;
  tourPeople?: number;
  tourLodging?: boolean;
  tourLodgingPref?: string;
  notes: string[];
  lastInteractionDate: string; // ISO String
  gdprConsent?: boolean;
  tourAgent?: string;
  tourVisitedProperties?: string[];
}

export const PROVINCE_REGIONS: Record<string, string[]> = {
  "San José": ["Barrio Escalante", "Escazú", "Santa Ana", "San José Centro", "Curridabat", "Pérez Zeledón"],
  "Alajuela": ["Atenas", "Alajuela Centro", "San Carlos", "Grecia", "Orotina"],
  "Cartago": ["Cartago Centro", "Tres Ríos", "Turrialba", "Paraíso"],
  "Heredia": ["Heredia Centro", "Belén", "Santo Domingo", "San Isidro"],
  "Guanacaste": ["Papagayo Peninsula", "Nosara", "Tamarindo", "Liberia", "Flamingo", "Playas del Coco"],
  "Puntarenas": ["Santa Teresa", "Manuel Antonio", "Monteverde", "Jacó", "Quepos", "Uvita", "Dominical"],
  "Limón": ["Puerto Viejo", "Limón Centro", "Cahuita", "Tortuguero"]
};

const SEEDED_PROPERTIES: Property[] = [
  {
    id: "villa-morpho",
    name: "Villa Morpho",
    location: "Papagayo Peninsula",
    price: 12500000,
    sqft: 8500,
    suites: 6,
    vibeTags: ["Oceanfront", "Infinity View", "Eco-Luxury"],
    description: "A breathtaking architectural masterpiece designed to mimic the wings of a Morpho butterfly. Features seamless indoor-outdoor living with panoramic ocean views.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Villa Exclusiva",
    segment: "Luxury",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Destacada",
    approxLocation: "Bahía Papagayo, Guanacaste",
    elevationM: 45,
    airportDistKm: 220,
    airportTimeMin: 210,
    closestCity: "Liberia",
    cityDistKm: 35,
    medicalDistMin: 20,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "obsidian-canopy",
    name: "The Obsidian Canopy",
    location: "Santa Teresa",
    price: 8900000,
    sqft: 6200,
    suites: 5,
    vibeTags: ["Jungle Brutalism", "Surf Access", "Minimalist"],
    description: "Striking black concrete structures hidden within the dense jungle. Designed for ultimate privacy while remaining steps away from world-class surf.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Playa Carmen, Santa Teresa",
    elevationM: 15,
    airportDistKm: 280,
    airportTimeMin: 300,
    closestCity: "Cobano",
    cityDistKm: 12,
    medicalDistMin: 15,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "quepos-zenith",
    name: "Quepos Zenith",
    location: "Manuel Antonio",
    price: 15000000,
    sqft: 12000,
    suites: 8,
    vibeTags: ["Helipad Access", "Cliffside", "Panoramic"],
    description: "Perched on the highest cliff in Manuel Antonio, Zenith offers unparalleled views of the Pacific Ocean and a private path to a secluded beach.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Villa Exclusiva",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Opcionada",
    approxLocation: "Área de Reserva, Manuel Antonio",
    elevationM: 80,
    airportDistKm: 160,
    airportTimeMin: 150,
    closestCity: "Quepos",
    cityDistKm: 7,
    medicalDistMin: 10,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "guanacaste-gold",
    name: "Guanacaste Gold Estate",
    location: "Papagayo Peninsula",
    price: 22000000,
    sqft: 15500,
    suites: 10,
    vibeTags: ["Ultra-Luxury", "Private Beach", "Yacht Mooring"],
    description: "The crown jewel of Papagayo. This estate features its own private white-sand beach, a mega-yacht mooring, and a multi-level cascading infinity pool.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Villa Exclusiva",
    segment: "Luxury",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Península Papagayo, Guanacaste",
    elevationM: 20,
    airportDistKm: 215,
    airportTimeMin: 200,
    closestCity: "Liberia",
    cityDistKm: 32,
    medicalDistMin: 25,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "cloud-forest",
    name: "Cloud Forest Sanctuary",
    location: "Monteverde",
    price: 5500000,
    sqft: 7000,
    suites: 4,
    vibeTags: ["High Altitude", "Sustainable", "Glass House"],
    description: "Suspended in the misty canopy, this glass-walled sanctuary blurs the line between the luxurious interior and the ancient, vibrant cloud forest outside.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Cabaña",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Reserva Nubosa, Monteverde",
    elevationM: 1420,
    airportDistKm: 135,
    airportTimeMin: 140,
    closestCity: "Santa Elena",
    cityDistKm: 4,
    medicalDistMin: 8,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "escalante-apex",
    name: "Escalante Apex Penthouse",
    location: "Barrio Escalante",
    price: 3200000,
    sqft: 4500,
    suites: 3,
    vibeTags: ["Skyline View", "Smart Home", "Gastronomic Center"],
    description: "The absolute height of urban sophistication. A multi-level penthouse in the heart of San José's culinary district with a private rooftop pool.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Luxury",
    province: "San José",
    lifestyle: "Ciudad",
    status: "Disponible",
    approxLocation: "Barrio Escalante, San José",
    elevationM: 1160,
    airportDistKm: 18,
    airportTimeMin: 30,
    closestCity: "San José Centro",
    cityDistKm: 2,
    medicalDistMin: 5,
    hasFiberOptic: true,
    hasStarlink: false,
  },
  {
    id: "nosara-flow",
    name: "Nosara Flow Villa",
    location: "Nosara",
    price: 6800000,
    sqft: 5800,
    suites: 5,
    vibeTags: ["Wellness", "Open Air", "Yoga Pavilion"],
    description: "Built for harmony and health. Features a dedicated yoga pavilion, salt-water lap pool, and organic gardens, all within walking distance to Guiones.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Quinta de Descanso",
    segment: "Luxury",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Playa Guiones, Nosara",
    elevationM: 35,
    airportDistKm: 250,
    airportTimeMin: 270,
    closestCity: "Nosara Centro",
    cityDistKm: 3,
    medicalDistMin: 10,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "casa-jade",
    name: "Casa Jade",
    location: "Santa Teresa",
    price: 4900000,
    sqft: 4200,
    suites: 4,
    vibeTags: ["Tropical Modernism", "Secluded", "Infinity Pool"],
    description: "A masterclass in tropical modernism. Local teak, poured concrete, and lush indoor gardens create a tranquil oasis hidden from the world.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Vendida",
    approxLocation: "Malpaís, Santa Teresa",
    elevationM: 50,
    airportDistKm: 285,
    airportTimeMin: 310,
    closestCity: "Cobano",
    cityDistKm: 15,
    medicalDistMin: 20,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "papagayo-point",
    name: "Point of Papagayo",
    location: "Papagayo Peninsula",
    price: 18500000,
    sqft: 11000,
    suites: 7,
    vibeTags: ["Peninsula Tip", "270° Views", "Golf Cart Access"],
    description: "Situated on the very tip of a private peninsula. Every room offers a different perspective of the Pacific Ocean and the rugged Guanacaste coastline.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Villa Exclusiva",
    segment: "Luxury",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Extremo Península, Papagayo",
    elevationM: 65,
    airportDistKm: 222,
    airportTimeMin: 215,
    closestCity: "Liberia",
    cityDistKm: 38,
    medicalDistMin: 22,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "manuel-antonio-reserve",
    name: "The Reserve",
    location: "Manuel Antonio",
    price: 9200000,
    sqft: 8000,
    suites: 6,
    vibeTags: ["Wildlife Integration", "Canopy Walkway", "Exclusive"],
    description: "Bordering the national park, this estate is frequently visited by monkeys and sloths. Includes a private canopy bridge connecting the main house to the guest suites.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Quinta",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Linderos de Parque, Manuel Antonio",
    elevationM: 90,
    airportDistKm: 165,
    airportTimeMin: 155,
    closestCity: "Quepos",
    cityDistKm: 9,
    medicalDistMin: 12,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "escalante-vault",
    name: "The Vault",
    location: "Barrio Escalante",
    price: 2800000,
    sqft: 3800,
    suites: 2,
    vibeTags: ["Industrial Chic", "Art Collector", "City Center"],
    description: "A converted historical building turned into a sprawling, industrial-chic loft. Designed specifically for displaying large-scale contemporary art.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Terreno de Montaña",
    segment: "Luxury",
    province: "San José",
    lifestyle: "Ciudad",
    status: "Disponible",
    approxLocation: "Zona Gastronómica, Escalante",
    elevationM: 1150,
    airportDistKm: 19,
    airportTimeMin: 32,
    closestCity: "San José Centro",
    cityDistKm: 3,
    medicalDistMin: 6,
    hasFiberOptic: true,
    hasStarlink: false,
  },
  {
    id: "nosara-horizon",
    name: "Horizon House",
    location: "Nosara",
    price: 7500000,
    sqft: 6500,
    suites: 5,
    vibeTags: ["Sunset Facing", "Minimalist", "Surfer's Dream"],
    description: "Characterized by its massive cantilevered roof that seems to float against the horizon. The ultimate vantage point for Nosara's legendary sunsets.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Luxury",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Opcionada",
    approxLocation: "Peladas, Nosara",
    elevationM: 40,
    airportDistKm: 248,
    airportTimeMin: 265,
    closestCity: "Nosara Centro",
    cityDistKm: 2,
    medicalDistMin: 9,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "santa-teresa-cliff",
    name: "Cliffside Haven",
    location: "Santa Teresa",
    price: 11000000,
    sqft: 9000,
    suites: 6,
    vibeTags: ["Dramatic Elevation", "Private Funicular", "Ocean Sounds"],
    description: "Accessed via a private funicular, this multi-level compound cascades down a sheer cliff face, offering unparalleled privacy and drama.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Altos de Santa Teresa",
    elevationM: 110,
    airportDistKm: 282,
    airportTimeMin: 305,
    closestCity: "Cobano",
    cityDistKm: 14,
    medicalDistMin: 18,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "papagayo-breeze",
    name: "Papagayo Breeze",
    location: "Papagayo Peninsula",
    price: 14000000,
    sqft: 10500,
    suites: 7,
    vibeTags: ["Marina Views", "Family Estate", "Resort Amenities"],
    description: "A sweeping, elegant estate designed to capture the cross-breezes. Overlooks the prestigious marina and includes access to world-class resort amenities.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Luxury",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Vendida",
    approxLocation: "Marina Papagayo, Guanacaste",
    elevationM: 30,
    airportDistKm: 218,
    airportTimeMin: 205,
    closestCity: "Liberia",
    cityDistKm: 34,
    medicalDistMin: 24,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "manuel-antonio-hideaway",
    name: "The Hideaway",
    location: "Manuel Antonio",
    price: 4200000,
    sqft: 4000,
    suites: 3,
    vibeTags: ["Intimate", "Rainforest", "Creek-side"],
    description: "An intimate, beautifully crafted wooden home nestled next to a pristine rainforest creek. The sound of running water provides a constant, soothing soundtrack.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Cabaña",
    segment: "Luxury",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Valle Verde, Manuel Antonio",
    elevationM: 95,
    airportDistKm: 162,
    airportTimeMin: 152,
    closestCity: "Quepos",
    cityDistKm: 8,
    medicalDistMin: 11,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "monteverde-nest",
    name: "Monteverde Cozy Nest",
    location: "Monteverde",
    price: 280000,
    sqft: 1200,
    suites: 2,
    vibeTags: ["Cozy", "Mist Vibe", "Eco-Friendly"],
    description: "A gorgeous wooden cabin nestled in the cool mist of Monteverde. Perfect as a vacation escape or an entry-level rental ready property.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Cabaña",
    segment: "Standard",
    province: "Puntarenas",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Santa Elena, Monteverde",
    elevationM: 1410,
    airportDistKm: 138,
    airportTimeMin: 145,
    closestCity: "Santa Elena",
    cityDistKm: 2,
    medicalDistMin: 5,
    hasFiberOptic: true,
    hasStarlink: false,
  },
  {
    id: "nosara-lot",
    name: "Guiones Surf Lot",
    location: "Nosara",
    price: 145000,
    sqft: 8000,
    suites: 0,
    vibeTags: ["Build Ready", "Walk to Surf", "Ocean Breeze"],
    description: "An exceptional, flat building lot located just a short walk to the main surf break at Guiones. Power and water connections ready.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Lote",
    segment: "Standard",
    province: "Guanacaste",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Playa Guiones, Nosara",
    elevationM: 15,
    airportDistKm: 252,
    airportTimeMin: 275,
    closestCity: "Nosara Centro",
    cityDistKm: 4,
    medicalDistMin: 12,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "escalante-loft",
    name: "Urban Nest Loft",
    location: "Barrio Escalante",
    price: 380000,
    sqft: 1800,
    suites: 2,
    vibeTags: ["Urban", "Gastronomic", "Fiber Optic"],
    description: "Modern, high-ceiling loft in the heart of Barrio Escalante's food district. Incredible light and walking distance to all services.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Casa",
    segment: "Standard",
    province: "San José",
    lifestyle: "Ciudad",
    status: "Disponible",
    approxLocation: "Barrio Escalante, San José",
    elevationM: 1155,
    airportDistKm: 18,
    airportTimeMin: 30,
    closestCity: "San José Centro",
    cityDistKm: 2,
    medicalDistMin: 5,
    hasFiberOptic: true,
    hasStarlink: false,
  },
  {
    id: "atenas-quinta",
    name: "Quinta del Sol",
    location: "Atenas",
    price: 720000,
    sqft: 3500,
    suites: 3,
    vibeTags: ["Best Climate", "Fruit Trees", "Panoramic Views"],
    description: "Charming country estate with mature fruit trees and panoramic mountain view. Located in Atenas, known for having the best climate in Costa Rica.",
    image: "/images/jungle.png",
    panorama: "/panoramas/default.jpg",
    type: "Quinta de Descanso",
    segment: "Standard",
    province: "Alajuela",
    lifestyle: "Naturaleza",
    status: "Disponible",
    approxLocation: "Altos de Atenas, Alajuela",
    elevationM: 720,
    airportDistKm: 28,
    airportTimeMin: 35,
    closestCity: "Atenas Centro",
    cityDistKm: 3,
    medicalDistMin: 8,
    hasFiberOptic: true,
    hasStarlink: true,
  },
  {
    id: "heredia-bodega",
    name: "Heredia Industrial Hub",
    location: "Heredia Centro",
    price: 320000,
    sqft: 5000,
    suites: 0,
    vibeTags: ["Security 24/7", "High Ceiling", "Heavy Transport Access"],
    description: "Spacious industrial warehouse located in Heredia's prime logistics park. High ceilings, 24/7 security, and reinforced concrete floors perfect for distribution.",
    image: "/images/minimalist.png",
    panorama: "/panoramas/default.jpg",
    type: "Bodega",
    segment: "Commercial",
    province: "Heredia",
    lifestyle: "Ciudad",
    status: "Disponible",
    approxLocation: "Zona Industrial, Heredia",
    elevationM: 1150,
    airportDistKm: 12,
    airportTimeMin: 20,
    closestCity: "Heredia Centro",
    cityDistKm: 2,
    medicalDistMin: 5,
    hasFiberOptic: true,
    hasStarlink: false,
  },
  {
    id: "sanjose-edificio",
    name: "Sabana Corporate Plaza",
    location: "San José Centro",
    price: 850000,
    sqft: 12000,
    suites: 0,
    vibeTags: ["Corporate Hub", "High ROI", "Downtown"],
    description: "A three-story commercial building ideal for corporate offices or a medical clinic. Strategic location near La Sabana with high visibility and parking.",
    image: "/images/ocean.png",
    panorama: "/panoramas/default.jpg",
    type: "Edificio",
    segment: "Commercial",
    province: "San José",
    lifestyle: "Ciudad",
    status: "Disponible",
    approxLocation: "Sabana Norte, San José",
    elevationM: 1130,
    airportDistKm: 15,
    airportTimeMin: 22,
    closestCity: "San José Centro",
    cityDistKm: 1,
    medicalDistMin: 3,
    hasFiberOptic: true,
    hasStarlink: true,
  }
];

export const PROPERTIES: Property[] = SEEDED_PROPERTIES.map((p, idx) => ({
  ...p,
  refCode: `REF-${String(idx + 1).padStart(2, "0")}`
}));
